### ISSUE TITLE
split "First Contact" tour

### ISSUE THREAD

**Issue by plegall** [Piwigo/TakeATour#2]
This tour is "far" too long for a first contact. All what is inside is interesting, but not as a "first contact". This tour should be splitted to be more efficient and if we want people to see all the steps through several tours.

**Comment by plegall** [comment]
@flop25 please give a first look at this "split" First Contact tour, into 5 autonomous tours.

**Comment by flop25** [comment]
I've read the code. Sounds perfect since you even improved the code
I just would change the  
`name: "first_contact"`
and
`onEnd: function (tour) {window.location = "{/literal}{$ABS_U_ADMIN}{literal}admin.php?page=plugin-TakeATour&tour_ended=first_contact"},`
with the real name (config...)

It doesn't matter for now but maybe one day the core or an extension would need to behave differently if a specific tour is launched.

**Comment by plegall** [comment]
OK, done :-)
